### ISSUE TITLE
Compatibility with react version 17 and changing colour

### ISSUE THREAD

**Issue by dav1d-wright** [harunurhan/react-latex-next#30]
Hi, and thanks for creating this nice package!

I have found that this package depends on react version 15 or 16, I have managed to install  and use it with react version 17 using `npm install --force`, as another package that I use depends on that version. I reckon it should be possible to just add version 17 to the possible versions in the dependency list.

Also I have a question that I couldn't answer by looking at your code (I'm not really much of a react expert): can you tell me how I could change the font colour of the rendered LaTeX?

**Comment by harunurhan** [comment]
@dav1d-wright 

I added react `v17` to the peer deps, you can install `v2.1.0` and try it out.

And for the colors, how ever you're styling rest of the your app should work just fine.

For example if you have something like that in your app.
```jsx
<p>
  <Latex>{aStringWithLaTeX}</Latex>
</p>
```

You can just do, if you are using CSS
```jsx
<p className="a-class-name-with-text-color">
  <Latex>{aStringWithLaTeX}</Latex>
</p>
```

Or if you prefer `style` prop
```jsx
<p style={{ color: 'red' }}>
  <Latex>{aStringWithLaTeX}</Latex>
</p>
```

**Comment by dav1d-wright** [comment]
Fantastic, thank you very much!
