### ISSUE TITLE
Update to newer versions of React. Can't use the lib in React ^18.2.0

### ISSUE THREAD

**Issue by MartinLBarranco** [harunurhan/react-latex-next#40]
Update to newer versions of React. Can't use the lib in React ^18.2.0

**Comment by harunurhan** [comment]
We already have `react 18` in the peer deps: https://github.com/harunurhan/react-latex-next/blob/6772e382348204c165d69f25b589d5f7336a45cc/package.json#L34

Which version of `react-latex-next` are you on?
