### ISSUE TITLE
Curly braces conflict

### ISSUE THREAD

**Issue by nahasco** [harunurhan/react-latex-next#43]
Not sure why I a missing here but LateX has curly braces and these conflict with React since React sees curly braces as variables.

For example:

`
% \f is defined as #1f(#2) using the macro
\f\relax{x} = \int_{-\infty}^\infty
    \f\hat\xi\,e^{2 \pi i \xi x}
    \,d\xi
`

Will not work.

**Comment by harunurhan** [comment]
You should be able to avoid this by having your LaTex as a string literal?

```
<Latex>{'my LaTeX string with { and }'}</Latex>
```

Btw overall your LaTeX seems incorrect apart from this issue.

**Comment by nahasco** [comment]
That's right.  
Thank you for the great package!
