### ISSUE TITLE
Normal text also showing up alongwith rendered LaTeX

### ISSUE THREAD

**Issue by gurbaaz27** [harunurhan/react-latex-next#44]
First of all, thank you for this easy-to-use great package!

I am using this to render some text in $\LaTeX$, and I don't know why but the rendered page is showing both the mathematical expression in LaTeX form as well as normal text form.

NextJS Code Snippet:

```javascript
import Latex from "react-latex-next"

...
<p className="py-6 text-base sm:text-lg"><Latex>{problem.description || ""}</Latex></p>
...
``` 

where 

`problem.description` = "You are given an urn with 100 balls (50 black and 50 white). You pick balls from urn one by one without replacements until all the balls are out. A black followed by a white or a white followed by a black is "a colour change". Calculate the expected number of colour changes if the balls are being picked randomly from the urn. $3x + 2 = 5$"

![image](https://user-images.githubusercontent.com/60743677/233796431-dfd0a29d-af96-4d68-bcaa-c6fd880e06a2.png)

Any help would be appreciated.

**Comment by harunurhan** [comment]
Can you copy paste the raw text that you are passing down to the `Latex` component?

@gurbaaz27

**Comment by gurbaaz27** [comment]
Raw text of problem description is 

```
You are given an urn with 100 balls (50 black and 50 white). You pick balls from urn one by one without
replacements until all the balls are out. A black followed by a white or a white followed by a black is 
"a colour change". Calculate the expected number of colour changes if the balls are being picked
randomly from the urn. $3x + 2 = 5$
```

**Comment by harunurhan** [comment]
I copy-pasted this to the [playground](https://react-latex.netlify.app/), looks like it is working as expected.

<img width="781" alt="Screenshot 2023-04-30 at 20 40 50" src="https://user-images.githubusercontent.com/4868667/235370645-c96e802c-25b9-4e6e-a5e6-34a1f225b44e.png">

And here you can see the code as a reference how playground is rendering the text input: https://github.com/harunurhan/react-latex-next/blob/master/example/src/App.js

**Comment by groupsvkg** [comment]
I had the similar issue. To fix this I installed `katex` package and imported `import 'katex/dist/katex.min.css'`

**Comment by harunurhan** [comment]
Thanks! this is part of the README but perhaps I could make it a bit more obvious.
