### ISSUE TITLE
NextJS 13, "use client", and TypeError

### ISSUE THREAD

**Issue by vanyabrucker** [harunurhan/react-latex-next#48]
I always got: `TypeError: Object prototype may only be an Object or null: undefined`

Had to use "use client" in my Next 13 app to make it work. You can read more about "use client" [here](https://nextjs.org/docs/app/building-your-application/rendering/client-components#using-client-components-in-nextjs).

Is this on purpose?

**Comment by harunurhan** [comment]
@vanyabrucker not familiar with RSC yet, so they might have a limitation which `Latex` is hitting, but I'll try to have a look.

**Comment by harunurhan** [comment]
I'll try to publish a release soon.
