### ISSUE TITLE
Latex Font

### ISSUE THREAD

**Issue by MuyiwaJohnson** [harunurhan/react-latex-next#52]
Hi. Is there a way to override the default latex Font size

**Comment by harunurhan** [comment]
You can just use `css` to change the font-size, basically something like below.

```jsx
<div style={{ fontSize: 10em }}>
  <Latex>Formula: $3 \times 5$</Latex>
</div>
```

I'll expose `style` and `className` props for `Latex` at some point, so that it doesn't need to be wrapped by an html element to be styled.

Please re-open if you this doesn't work for you.
